In [3]:
import os
import math
import numpy as np
# Please put your input file in the same folder as this Jupyter notebook file.
# Please do not change any other code
# You only need to complete the functions with TODO
# You can simply run the Q1/Q2/Q3_test() to test your function

In [4]:
def Q1_input(file_path):
    input_list = []
    with open(file_path, 'r') as file:
        for line in file:
            values = line.strip().split(',')
            if len(values) == 3:
                try:
                    Y = int(values[0])
                    Co = int(values[1])
                    Cg = int(values[2])
                    input_list.append((Y, Co, Cg))
                except ValueError:
                    print(f"Invalid line: {line}")
    return input_list


def Q1_test():
    input_file = "q1_input.txt"
    yco_cg_list = Q1_input(input_file)

    for Y, Co, Cg in yco_cg_list:
        YUV = Q1(Y, Co, Cg)
        print(f"YCoCg: ({Y}, {Co}, {Cg}) -> YUV: (Y={YUV[0]}, U={YUV[1]}, V={YUV[2]})")


In [5]:
def Q1(Y, Co, Cg):
    # TODO:
    # Conversion formula from Y Co Cg to YUV
    YCoCg_RGB_matrix = np.array([
        [1,  1,  0],
        [-1,  1, -1],
        [-1, 1,  1]
    ])

    RGB_YUV_matrix = np.array([
        [0.299, 0.587, 0.114],
        [-0.299, -0.587, 0.886],
        [0.701, -0.587, -0.114]
    ])

    CgYCo = np.array([Cg, Y, Co])
    G, B, R = np.dot(YCoCg_RGB_matrix, CgYCo)

    RGB = np.array([R, G, B])
    Y, U, V = np.dot(RGB_YUV_matrix, RGB)

    return (Y, U, V)


In [6]:
Q1_test()

YCoCg: (100, 5, 5) -> YUV: (Y=101.795, U=-11.794999999999996, V=-1.7950000000000024)


In [7]:
dither_matrix = np.array([
    [0, 3],
    [2, 1]
])

def Q2_input(file_path):
    image = []
    with open(file_path, 'r') as file:
        for line in file:
            row = []
            values = line.strip().split(',')
            for item in values:
                row.append(int(item))
            image.append(row)
    return np.array(image)

def Q2_test():
    file_path = "q2_input.txt"
    input_image = Q2_input(file_path)
    print("input image:\n",input_image)
    dithering_res = dithering(input_image,dither_matrix)
    ordered_dithering_res = ordered_dithering(input_image,dither_matrix)
    print("dithering:\n",dithering_res)
    print("ordered_dithering:\n",ordered_dithering_res)

In [8]:
def dithering(input_image,dither_matrix):
    #TODO:
    # Function for dithering
    ranges = np.linspace(0, 256, 6)
    mapped = np.digitize(input_image, ranges) - 1

    h, w = input_image.shape
    dithered_img = np.zeros((h * 2, w * 2), dtype=np.uint8)

    for y in range(h):
        for x in range(w):
            pixel = mapped[y, x]  # Get the pixel intensity
            # Apply the threshold rule
            new_block = (pixel > dither_matrix).astype(np.uint8)

            # Store the 2x2 block in the final image
            dithered_img[y*2:y*2+2, x*2:x*2+2] = new_block

    return dithered_img

def ordered_dithering(input_image,dither_matrix):
    #TODO:
    # Function for ordered dithering
    n = np.size(dither_matrix, axis=0)
    ranges = np.linspace(0, 256, 6)
    mapped = np.digitize(input_image, ranges) - 1

    h, w = input_image.shape
    dithered_img = np.zeros((h, w), dtype=np.uint8)
    for y in range(h):
        for x in range(w):
            i = x % n
            j = y % n
            pixel = mapped[y, x]
            dither_entry = dither_matrix[j, i]
            if (pixel > dither_entry):
                dithered_img[y, x] = 1
            else:
                dithered_img[y, x] = 0

    return dithered_img

In [9]:
Q2_test()

input image:
 [[ 12 112 233 100]
 [158 120  10 210]
 [ 31 190  71  81]
 [  1   1   1   1]]
dithering:
 [[0 0 1 0 1 1 1 0]
 [0 0 0 1 1 1 0 0]
 [1 0 1 0 0 0 1 1]
 [1 1 0 1 0 0 1 1]
 [0 0 1 0 1 0 1 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
ordered_dithering:
 [[0 0 1 0]
 [1 1 0 1]
 [0 0 1 0]
 [0 0 0 0]]


In [23]:
def Q3_input(file_path):
    string = []
    with open(file_path, 'r') as file:
        for line in file:
            string.append(line)
    return string


def Q3_test():

    file_path = "q3_input.txt"

    input_list = Q3_input(file_path)
    for input_string in input_list:
        print("input string: ",input_string)
        print("first order entropy:",first_order_entropy(input_string))
        print("second order entropy:",second_order_entropy(input_string))
        print("average codeword length:",huffman_length(input_string))
        print("joint average length:",joint_huffman_length(input_string))



In [24]:
def first_order_entropy(string):
    # TODO:
    # Function to calculate first-order entropy
    n = len(string)
    freqency = {}
    for char in string:
        if char in freqency:
            freqency[char] += 1
        else:
            freqency[char] = 1
    entropy = -sum((char_count / n) * math.log2(char_count / n) for char_count in freqency.values())

    return entropy


def second_order_entropy(string):
    # TODO:
    # Function to calculate second-order entropy
    entropy = 0

    return entropy




def huffman_length(string):
    # TODO:
    # Function to calculate average codeword length
    avg_length = 0

    return avg_length


def joint_huffman_length(string):
    # TODO:
    # Function to calculate average codeword length for 2 symbol joint Huffman coding
    joint_avg_length = 0

    return joint_avg_length



In [25]:
Q3_test()

input string:  AABB
first order entropy: 1.0
second order entropy: 0
average codeword length: 0
joint average length: 0


In [ ]:
# (3) Discuss any issues/interesting observations in your implementation.


In [ ]:
# (4) Experiment different randomly/non randomly generated inputs, and discuss your observations.
# You can implement your experiment here

